version: '3.8'

services:
  db:
    image: postgres:16.0
    container_name: studentvertx
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
